### ISSUE TITLE
Not all companies in 2018q4 data represented?

### ISSUE THREAD

**Issue by shaffner** [msperlin/GetEdgarData#3]
Executed:

`df_info<- get_info_companies(type_data='yearly',years=2017:2019)`

searched for Microsoft in the data download - not found.
`df_info %>% filter(grepl("microsoft",current_name,ignore.case=TRUE))`

downloaded the "2018q4.zip" SEC zip file from the [website.](https://www.sec.gov/dera/data/financial-statement-data-sets.html) Looked inside manually and Microsoft was indeed included in the file.  How many other companies are not included? And does this then spread to the financial data as well?

My version of GetEdgarData is 0.1 downloaded from GitHub on 30 Oct 2019.

**Comment by msperlin** [comment]
Hi shaffner, 

Thanks, I'll have a look.

**Comment by msperlin** [comment]
Shaffner,

The getedgardata package is now discontinued and in wont be fixing bugs. Have a look at a better source of financial data with simfinR, also authored by me. 

https://www.msperlin.com/blog/post/2019-11-01-new-package-simfinr/
